// GENERATED by tools/gen-icons.py — see design/icons.html for the source art.
#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t icon_stand;
extern const lv_image_dsc_t icon_water;
extern const lv_image_dsc_t icon_roll;
extern const lv_image_dsc_t icon_snack;
extern const lv_image_dsc_t icon_lunch;
extern const lv_image_dsc_t icon_stretch;
