// GENERATED by tools/gen-fixtures.mjs from fixtures/derive/*.json — do not edit.
#pragma once

#include "wfh_types.h"

typedef struct { const char *action, *kind, *ts, *slot; } fx_event_t;
typedef struct { const char *key; const char *value; } fx_kv_t;
typedef struct { const char *key; int value; } fx_ki_t;
typedef struct { const char *key; long long value; } fx_ke_t;

typedef struct {
    const char *name, *why, *tz, *date, *now, *mode, *work_start, *work_end;
    int grace_min;                                  // -1 = use config default
    const action_def_t *actions;  int n_actions;    // NULL = shipping config
    const fx_event_t   *events;   int n_events;
    const fx_kv_t      *snoozes;  int n_snoozes;
    const fx_ki_t      *counts;   int n_counts;     // exhaustive
    const fx_ki_t      *skipped;  int n_skipped;    // exhaustive
    const fx_ki_t      *missed;   int n_missed;     // exhaustive
    const fx_kv_t      *next;     int n_next;       // partial
    const fx_ke_t      *next_epoch; int n_next_epoch;
    const char *const  *next_none;  int n_next_none;
    const char *const  *due;      int n_due;        // exact, ordered
} fixture_t;

static const action_def_t card_confirm_partial_actions[] = {
    { .id = "stand", .name = "Stand break", .target = 10, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 40 } },
    { .id = "water", .name = "Water", .target = 8, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 45 } },
    { .id = "roll", .name = "Shoulder roll", .target = 8, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 60 } },
};

static const fx_event_t card_confirm_partial_events[] = {
    { "stand", "done", "11:05", "11:00" },
    { "roll", "done", "11:05", "11:00" },
};

static const fx_ki_t card_confirm_partial_counts[] = {
    { "stand", 1 },
    { "roll", 1 },
};

static const fx_ki_t card_confirm_partial_missed[] = {
    { "stand", 2 },
    { "water", 1 },
    { "roll", 1 },
};

static const fx_kv_t card_confirm_partial_next[] = {
    { "stand", "11:45" },
    { "water", "11:15" },
    { "roll", "12:05" },
};

static const char *const card_confirm_partial_due[] = {
    "water",
};

static const fx_kv_t dst_day_before_next[] = {
    { "stand", "09:40" },
    { "water", "09:45" },
    { "roll", "10:00" },
    { "lunch", "13:00" },
};

static const fx_ke_t dst_day_before_next_epoch[] = {
    { "stand", 1774690800LL },
    { "lunch", 1774702800LL },
};

static const fx_kv_t dst_forward_next[] = {
    { "stand", "09:40" },
    { "water", "09:45" },
    { "roll", "10:00" },
    { "lunch", "13:00" },
};

static const fx_ke_t dst_forward_next_epoch[] = {
    { "stand", 1774773600LL },
    { "lunch", 1774785600LL },
};

static const action_def_t duplicate_event_actions[] = {
    { .id = "water", .name = "Water", .target = 8, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 45 } },
};

static const fx_event_t duplicate_event_events[] = {
    { "water", "done", "09:50", "09:45" },
    { "water", "done", "09:50", "09:45" },
};

static const fx_ki_t duplicate_event_counts[] = {
    { "water", 1 },
};

static const fx_kv_t duplicate_event_next[] = {
    { "water", "10:35" },
};

static const action_def_t fixed_done_early_actions[] = {
    { .id = "lunch", .name = "Lunch", .target = 1, .priority = 2, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_FIXED, .n_times = 1, .times = { "13:00" } } },
};

static const fx_event_t fixed_done_early_events[] = {
    { "lunch", "done", "12:40", "13:00" },
};

static const fx_ki_t fixed_done_early_counts[] = {
    { "lunch", 1 },
};

static const char *const fixed_done_early_next_none[] = {
    "lunch",
};

static const action_def_t interval_done_early_actions[] = {
    { .id = "water", .name = "Water", .target = 8, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 45 } },
};

static const fx_event_t interval_done_early_events[] = {
    { "water", "done", "09:50", "09:45" },
};

static const fx_ki_t interval_done_early_counts[] = {
    { "water", 1 },
};

static const fx_kv_t interval_done_early_next[] = {
    { "water", "10:35" },
};

static const fx_event_t replay_idempotent_events[] = {
    { "stand", "done", "09:45", "09:40" },
    { "water", "skip", "10:35", "10:30" },
    { "lunch", "done", "13:05", "13:00" },
};

static const fx_ki_t replay_idempotent_counts[] = {
    { "stand", 1 },
    { "lunch", 1 },
};

static const fx_ki_t replay_idempotent_skipped[] = {
    { "water", 1 },
};

static const fx_ki_t replay_idempotent_missed[] = {
    { "stand", 4 },
    { "water", 3 },
    { "roll", 3 },
};

static const fx_kv_t replay_idempotent_next[] = {
    { "stand", "13:45" },
    { "water", "13:30" },
    { "roll", "14:00" },
    { "snack", "15:30" },
    { "stretch", "16:30" },
};

static const char *const replay_idempotent_next_none[] = {
    "lunch",
};

static const char *const replay_idempotent_due[] = {
    "stretch",
    "snack",
    "stand",
    "water",
    "roll",
};

static const action_def_t snoozed_not_due_actions[] = {
    { .id = "stand", .name = "Stand break", .target = 10, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 40 } },
};

static const fx_kv_t snoozed_not_due_snoozes[] = {
    { "stand", "10:45" },
};

static const fx_ki_t snoozed_not_due_missed[] = {
    { "stand", 1 },
};

static const fx_kv_t snoozed_not_due_next[] = {
    { "stand", "11:00" },
};

static const fx_ki_t stretch_priority_missed[] = {
    { "stand", 2 },
    { "water", 2 },
    { "roll", 1 },
};

static const fx_kv_t stretch_priority_next[] = {
    { "stand", "11:40" },
    { "water", "12:00" },
    { "roll", "12:00" },
    { "snack", "15:30" },
    { "lunch", "13:00" },
    { "stretch", "16:30" },
};

static const char *const stretch_priority_due[] = {
    "stretch",
    "snack",
    "stand",
    "water",
    "roll",
};

static const action_def_t unanswered_past_slot_actions[] = {
    { .id = "stand", .name = "Stand break", .target = 10, .priority = 1, .flow = FLOW_TAP, .cadence = { .kind = CADENCE_INTERVAL, .every_min = 40 } },
};

static const fx_ki_t unanswered_past_slot_missed[] = {
    { "stand", 1 },
};

static const fx_kv_t unanswered_past_slot_next[] = {
    { "stand", "11:00" },
};

static const char *const unanswered_past_slot_due[] = {
    "stand",
};

static const fixture_t FIXTURES[] = {
    { .name = "card-confirm-partial", .why = "§6: Confirm logs the checked rows and leaves the rest due. Three actions were due at 11:05; stand and roll were ticked and confirmed, water was not. Water stays due (not skipped, not missed), and the two confirmed ones re-anchor off the 11:05 tap.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "11:05", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = card_confirm_partial_actions, .n_actions = 3,
      .events = card_confirm_partial_events, .n_events = 2,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = card_confirm_partial_counts, .n_counts = 2,
      .skipped = NULL, .n_skipped = 0,
      .missed = card_confirm_partial_missed, .n_missed = 3,
      .next = card_confirm_partial_next, .n_next = 3,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = NULL, .n_next_none = 0,
      .due = card_confirm_partial_due, .n_due = 1 },

    { .name = "dst-day-before", .why = "The control for dst-forward: the same wall-clock schedule one day earlier, still in GMT. Lunch is 1774702800 here and 1774785600 the next day — exactly 82800s (23h) apart, not 86400s. A UTC-by-hand implementation passes one of these two fixtures and fails the other.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-03-28", .now = "09:30", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = NULL, .n_actions = 0,
      .events = NULL, .n_events = 0,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = NULL, .n_counts = 0,
      .skipped = NULL, .n_skipped = 0,
      .missed = NULL, .n_missed = 0,
      .next = dst_day_before_next, .n_next = 4,
      .next_epoch = dst_day_before_next_epoch, .n_next_epoch = 2,
      .next_none = NULL, .n_next_none = 0,
      .due = NULL, .n_due = 0 },

    { .name = "dst-forward", .why = "2026-03-29 is the UK spring-forward Sunday (01:00 GMT becomes 02:00 BST). The working day is entirely inside BST, so every slot must land at its authored WALL-CLOCK time — an hour earlier in UTC than the day before. The epochs below are computed by hand, not taken from the code, so this is a real anchor rather than a mirror.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-03-29", .now = "09:30", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = NULL, .n_actions = 0,
      .events = NULL, .n_events = 0,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = NULL, .n_counts = 0,
      .skipped = NULL, .n_skipped = 0,
      .missed = NULL, .n_missed = 0,
      .next = dst_forward_next, .n_next = 4,
      .next_epoch = dst_forward_next_epoch, .n_next_epoch = 2,
      .next_none = NULL, .n_next_none = 0,
      .due = NULL, .n_due = 0 },

    { .name = "duplicate-event", .why = "§3.4: (action, slot) is unique, so a log carrying the same answer twice — a double-tap that slipped past the constraint, a replayed row — still counts once. derive must not trust the log to be deduped for it.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "09:50", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = duplicate_event_actions, .n_actions = 1,
      .events = duplicate_event_events, .n_events = 2,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = duplicate_event_counts, .n_counts = 1,
      .skipped = NULL, .n_skipped = 0,
      .missed = NULL, .n_missed = 0,
      .next = duplicate_event_next, .n_next = 1,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = NULL, .n_next_none = 0,
      .due = NULL, .n_due = 0 },

    { .name = "fixed-done-early", .why = "§5.3: a fixed action must NOT re-anchor. Lunch eaten at 12:40 answers the 13:00 slot and the day is done with lunch. Anchoring here would walk back to 13:00 forever, so this guards a hang as well as a miscount.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "12:45", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = fixed_done_early_actions, .n_actions = 1,
      .events = fixed_done_early_events, .n_events = 1,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = fixed_done_early_counts, .n_counts = 1,
      .skipped = NULL, .n_skipped = 0,
      .missed = NULL, .n_missed = 0,
      .next = NULL, .n_next = 0,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = fixed_done_early_next_none, .n_next_none = 1,
      .due = NULL, .n_due = 0 },

    { .name = "interval-done-early", .why = "§5.3: an interval action done early re-anchors from the tap. Water's grid slot was 09:45 and the next would have been 10:30; drinking at 09:50 pushes it to 10:35.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "09:50", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = interval_done_early_actions, .n_actions = 1,
      .events = interval_done_early_events, .n_events = 1,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = interval_done_early_counts, .n_counts = 1,
      .skipped = NULL, .n_skipped = 0,
      .missed = NULL, .n_missed = 0,
      .next = interval_done_early_next, .n_next = 1,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = NULL, .n_next_none = 0,
      .due = NULL, .n_due = 0 },

    { .name = "replay-idempotent", .why = "The property behind every retry in the system: applying the whole log twice must produce the identical view. Run in replay mode, so the harness also derives over a doubled log and compares. Uses the real shipping schedule rather than a toy one.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "13:10", .mode = "replay",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = NULL, .n_actions = 0,
      .events = replay_idempotent_events, .n_events = 3,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = replay_idempotent_counts, .n_counts = 2,
      .skipped = replay_idempotent_skipped, .n_skipped = 1,
      .missed = replay_idempotent_missed, .n_missed = 3,
      .next = replay_idempotent_next, .n_next = 5,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = replay_idempotent_next_none, .n_next_none = 1,
      .due = replay_idempotent_due, .n_due = 5 },

    { .name = "snoozed-not-due", .why = "§6 Delay-all: a snoozed action inside its window is neither due nor missed — it is quietly deferred. The earlier slot, whose window already closed, is still a miss; snoozing does not retroactively forgive it.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "10:30", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = snoozed_not_due_actions, .n_actions = 1,
      .events = NULL, .n_events = 0,
      .snoozes = snoozed_not_due_snoozes, .n_snoozes = 1,
      .counts = NULL, .n_counts = 0,
      .skipped = NULL, .n_skipped = 0,
      .missed = snoozed_not_due_missed, .n_missed = 1,
      .next = snoozed_not_due_next, .n_next = 1,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = NULL, .n_next_none = 0,
      .due = NULL, .n_due = 0 },

    { .name = "stretch-priority", .why = "§6: a due stretch pre-empts the checklist, so it must sort first. At 11:35 five things are due on the real schedule; due[0] must be the stretch, and equal priorities must keep config order rather than shuffling between ticks.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "11:35", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = NULL, .n_actions = 0,
      .events = NULL, .n_events = 0,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = NULL, .n_counts = 0,
      .skipped = NULL, .n_skipped = 0,
      .missed = stretch_priority_missed, .n_missed = 3,
      .next = stretch_priority_next, .n_next = 6,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = NULL, .n_next_none = 0,
      .due = stretch_priority_due, .n_due = 5 },

    { .name = "unanswered-past-slot", .why = "§3.2: unanswered and past splits two ways. At 10:30 the 09:40 slot's window closed at 10:20 so it is a miss; the 10:20 slot's window runs to 11:00 so it is still due, not yet a miss.", .tz = "GMT0BST,M3.5.0/1,M10.5.0",
      .date = "2026-08-13", .now = "10:30", .mode = "once",
      .work_start = NULL, .work_end = NULL,
      .grace_min = -1,
      .actions = unanswered_past_slot_actions, .n_actions = 1,
      .events = NULL, .n_events = 0,
      .snoozes = NULL, .n_snoozes = 0,
      .counts = NULL, .n_counts = 0,
      .skipped = NULL, .n_skipped = 0,
      .missed = unanswered_past_slot_missed, .n_missed = 1,
      .next = unanswered_past_slot_next, .n_next = 1,
      .next_epoch = NULL, .n_next_epoch = 0,
      .next_none = NULL, .n_next_none = 0,
      .due = unanswered_past_slot_due, .n_due = 1 },
};

#define FIXTURE_COUNT 10
