// GENERATED by tools/gen-config.mjs from config/actions.json — do not edit.
// Edit the JSON and re-run `node tools/gen-config.mjs`; CI fails on a drift.
#pragma once

#include "wfh_types.h"

// Credentials live in the ignored wifi.g.h; a checkout without one is offline.
#if __has_include("wifi.g.h")
#include "wifi.g.h"
#else
#define WIFI_SSID ""
#define WIFI_PASS ""
#endif

#define ACTIONS_COUNT   6
#define STRETCH_COUNT   3

static const action_def_t ACTIONS[ACTIONS_COUNT] = {
    { .id = "stand", .name = "Stand break",
      .blurb = "Up on your feet for a minute.",
      .target = 10, .priority = 1, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_INTERVAL, .every_min = 40 } },

    { .id = "water", .name = "Water",
      .blurb = "Glass of water. Refill while you are up.",
      .target = 8, .priority = 1, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_INTERVAL, .every_min = 45 } },

    { .id = "roll", .name = "Shoulder roll",
      .blurb = "Ten slow rolls back, then drop the shoulders.",
      .target = 8, .priority = 1, .flow = FLOW_STRETCH,
      .cadence = { .kind = CADENCE_INTERVAL, .every_min = 60 } },

    { .id = "snack", .name = "Snack",
      .blurb = "Something small before the slump.",
      .target = 2, .priority = 2, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_FIXED, .n_times = 2, .times = { "10:45", "15:30" } } },

    { .id = "lunch", .name = "Lunch",
      .blurb = "Away from the desk.",
      .target = 1, .priority = 2, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_FIXED, .n_times = 1, .times = { "13:00" } } },

    { .id = "stretch", .name = "Stretches",
      .blurb = "Three stretches, about two minutes.",
      .target = 2, .priority = 3, .flow = FLOW_STRETCH,
      .cadence = { .kind = CADENCE_FIXED, .n_times = 2, .times = { "11:30", "16:30" } } },
};

static const stretch_def_t STRETCHES[STRETCH_COUNT] = {
    { .name = "Chin tucks", .seconds = 30, .cue = "Draw the chin straight back, hold, release. Resets a screen-jutted neck." },
    { .name = "Doorway pec stretch", .seconds = 40, .cue = "Forearms on the frame, step through, chest open. Both sides at once." },
    { .name = "Cat-cow", .seconds = 40, .cue = "All fours: arch up, dip down, with the breath. Loosens the sitting spine." },
};

static const settings_t SETTINGS_DEFAULT = {
    .work_start = "09:00",
    .work_end   = "18:00",
    .tz         = "GMT0BST,M3.5.0/1,M10.5.0",
    .grace_min  = 30,
    .wifi_ssid  = WIFI_SSID,
    .wifi_pass  = WIFI_PASS,
    .actions    = ACTIONS,
    .n_actions  = ACTIONS_COUNT,
};
