// GENERATED by tools/gen-config.mjs from config/actions.json — do not edit.
// Edit the JSON and re-run `node tools/gen-config.mjs`; CI fails on a drift.
#pragma once

#include "wfh_types.h"

typedef struct { const char *name; int seconds; const char *cue; } stretch_def_t;

#define ACTIONS_COUNT   6
#define STRETCH_COUNT   4

static const action_def_t ACTIONS[ACTIONS_COUNT] = {
    { .id = "stand", .name = "Stand break",
      .blurb = "Up on your feet for a minute.",
      .target = 10, .priority = 1, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_INTERVAL, .every_min = 40 } },

    { .id = "water", .name = "Water",
      .blurb = "Glass of water. Refill while you are up.",
      .target = 8, .priority = 1, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_INTERVAL, .every_min = 45 } },

    { .id = "roll", .name = "Shoulder roll",
      .blurb = "Ten slow rolls back, then drop the shoulders.",
      .target = 8, .priority = 1, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_INTERVAL, .every_min = 60 } },

    { .id = "snack", .name = "Snack",
      .blurb = "Something small before the slump.",
      .target = 2, .priority = 2, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_FIXED, .n_times = 2, .times = { "10:45", "15:30" } } },

    { .id = "lunch", .name = "Lunch",
      .blurb = "Away from the desk.",
      .target = 1, .priority = 2, .flow = FLOW_TAP,
      .cadence = { .kind = CADENCE_FIXED, .n_times = 1, .times = { "13:00" } } },

    { .id = "stretch", .name = "Stretches",
      .blurb = "Four stretches, about three minutes.",
      .target = 2, .priority = 3, .flow = FLOW_STRETCH,
      .cadence = { .kind = CADENCE_FIXED, .n_times = 2, .times = { "11:30", "16:30" } } },
};

static const stretch_def_t STRETCHES[STRETCH_COUNT] = {
    { .name = "Chin tucks", .seconds = 30, .cue = "Draw the chin straight back. Hold, release, repeat." },
    { .name = "Doorway pec stretch", .seconds = 40, .cue = "Forearms on the frame, step through, chest open." },
    { .name = "Cat-cow", .seconds = 40, .cue = "On all fours, arch and round with the breath." },
    { .name = "Hip flexor stretch", .seconds = 50, .cue = "Half kneel, tuck the pelvis, 25s each side." },
};

static const settings_t SETTINGS_DEFAULT = {
    .work_start = "09:00",
    .work_end   = "18:00",
    .tz         = "GMT0BST,M3.5.0/1,M10.5.0",
    .grace_min  = 30,
    .actions    = ACTIONS,
    .n_actions  = ACTIONS_COUNT,
};
