#!/usr/bin/env node
// config/actions.json -> firmware/main/actions.g.h   (§2.1)
//
// Transliteration only: no date arithmetic happens here. Times stay as
// "HH:MM" strings and are resolved by wfh_at_time() on the board, so there
// is exactly one implementation of local-time maths in the system.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'config/actions.json');
const out = resolve(root, 'firmware/main/actions.g.h');

const cfg = JSON.parse(readFileSync(src, 'utf8'));

// WiFi credentials never enter git: config/secrets.json is ignored and
// becomes firmware/main/wifi.g.h, also ignored (PLAN §11 step 10). With no
// secrets file the board builds offline and the clock keeps its seed.
const secretsPath = resolve(root, 'config/secrets.json');
const secrets = existsSync(secretsPath) ? JSON.parse(readFileSync(secretsPath, 'utf8')) : {};
const wifiOut = resolve(root, 'firmware/main/wifi.g.h');
const str = (s) => JSON.stringify(String(s));
const FLOWS = { tap: 'FLOW_TAP', stretch: 'FLOW_STRETCH' };

const cadence = (c) => {
  if (c.kind === 'interval') {
    return `{ .kind = CADENCE_INTERVAL, .every_min = ${c.everyMin} }`;
  }
  const times = c.times.map(str).join(', ');
  return `{ .kind = CADENCE_FIXED, .n_times = ${c.times.length}, .times = { ${times} } }`;
};

const actions = cfg.actions.map((a) => `    { .id = ${str(a.id)}, .name = ${str(a.name)},
      .blurb = ${str(a.blurb)},
      .target = ${a.target}, .priority = ${a.priority}, .flow = ${FLOWS[a.flow]},
      .cadence = ${cadence(a.cadence)} },`).join('\n\n');

const stretches = cfg.stretches.map((s) =>
  `    { .name = ${str(s.name)}, .seconds = ${s.seconds}, .cue = ${str(s.cue)} },`).join('\n');

writeFileSync(out, `// GENERATED by tools/gen-config.mjs from config/actions.json — do not edit.
// Edit the JSON and re-run \`node tools/gen-config.mjs\`; CI fails on a drift.
#pragma once

#include "wfh_types.h"

// Credentials live in the ignored wifi.g.h; a checkout without one is offline.
#if __has_include("wifi.g.h")
#include "wifi.g.h"
#else
#define WIFI_SSID ""
#define WIFI_PASS ""
#endif

#define ACTIONS_COUNT   ${cfg.actions.length}
#define STRETCH_COUNT   ${cfg.stretches.length}

static const action_def_t ACTIONS[ACTIONS_COUNT] = {
${actions}
};

static const stretch_def_t STRETCHES[STRETCH_COUNT] = {
${stretches}
};

static const settings_t SETTINGS_DEFAULT = {
    .work_start = ${str(cfg.workStart)},
    .work_end   = ${str(cfg.workEnd)},
    .tz         = ${str(cfg.tz)},
    .grace_min  = ${cfg.graceMin},
    .wifi_ssid  = WIFI_SSID,
    .wifi_pass  = WIFI_PASS,
    .actions    = ACTIONS,
    .n_actions  = ACTIONS_COUNT,
};
`);

writeFileSync(wifiOut, `// GENERATED by tools/gen-config.mjs from config/secrets.json — do not edit, do not commit.
#pragma once
#define WIFI_SSID ${str(secrets.wifi?.ssid ?? '')}
#define WIFI_PASS ${str(secrets.wifi?.pass ?? '')}
`);

console.log(`gen-config: ${cfg.actions.length} actions -> firmware/main/actions.g.h; wifi ${secrets.wifi?.ssid ? 'set' : 'unset'} -> firmware/main/wifi.g.h`);
