#!/usr/bin/env python3
"""design/icons/*.png -> firmware/main/icons/icons.c  (LVGL 9 A8 images)

Alpha-only, recoloured per action at runtime, so one asset serves whatever
tint the schedule gives it. Written against the lv_image_dsc_t in the
vendored LVGL rather than a converter's idea of it — the Geist fonts were
generated for LVGL 8 by a tool that still builds clean against 9 and then
renders nothing, and that is a mistake worth only making once.
"""
import pathlib, sys
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = ROOT / "design/icons"
OUT  = ROOT / "firmware/main/icons"
IDS  = ["stand", "water", "roll", "snack", "lunch", "stretch"]

OUT.mkdir(parents=True, exist_ok=True)
body, decls = [], []

for name in IDS:
    img = Image.open(SRC / f"{name}.png").convert("RGBA")
    w, h = img.size
    alpha = img.getchannel("A").tobytes()          # A8: one byte per pixel
    rows = ",\n    ".join(
        ", ".join(f"0x{a:02x}" for a in alpha[y*w:(y+1)*w]) for y in range(h))
    body.append(f"""static const uint8_t {name}_map[] = {{
    {rows}
}};

const lv_image_dsc_t icon_{name} = {{
    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,
                .flags = 0, .w = {w}, .h = {h}, .stride = {w}, .reserved_2 = 0 }},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};""")
    decls.append(f"extern const lv_image_dsc_t icon_{name};")
    print(f"{name}: {w}x{h}, {len(alpha)} bytes")

(OUT / "icons.c").write_text(
    "// GENERATED by tools/gen-icons.py from design/icons/*.png — do not edit.\n"
    '#include "icons.h"\n\n' + "\n\n".join(body) + "\n")
(OUT / "icons.h").write_text(
    "// GENERATED by tools/gen-icons.py — see design/icons.html for the source art.\n"
    "#pragma once\n\n#include \"lvgl.h\"\n\n" + "\n".join(decls) + "\n")
print(f"-> {OUT}/icons.c")
